/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import control.TaiKhoanDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TaiKhoan;
import support.BatNgoaiLe;
import support.OpenDB;
import view.login.FrmLogin;

/**
 *
 * @author MrDuc
 */
public class FrmAdmin extends javax.swing.JFrame {

    private Connection cnn;
    private PreparedStatement pr;
    private Statement st;
    private Vector<TaiKhoan> v = new Vector<>();
    private TaiKhoanDAO taiKhoanDAO = new TaiKhoanDAO();

    /**
     * Creates new form ManagerLogin
     */
    /*Hàm khởi tạo có tham số để truyền tài khoản đăng nhập vào frm*/
    public FrmAdmin(TaiKhoan taiKhoan) {
        super();
        initComponents();
        cnn = OpenDB.open();
        v = taiKhoanDAO.danhSachTaiKhoan();
        setTBUser();
        jlbTenAdmin.setText(taiKhoan.getHoTen());
    }

    public FrmAdmin() {
        super();
        initComponents();
        cnn = OpenDB.open();
        v = taiKhoanDAO.danhSachTaiKhoan();
        setTBUser();
    }

    /*Set bảng hiển thị dạnh sách các tài khoản có trong csdl*/
    public void setTBUser() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers("ID, UserName, PassWord, Họ tên, Địa chỉ, Số điện thoại, Chức vụ".split(","));
        for (TaiKhoan taiKhoan : v) {
            dtm.addRow(taiKhoan.getObject());
        }
        v = taiKhoanDAO.danhSachTaiKhoan();
        jtbUser.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbType = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jlbTenAdmin = new javax.swing.JLabel();
        jcbSearch = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpwPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jcbRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfHoTen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfDiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfSoDT = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUser = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xin chào:");

        jlbType.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Zoom-icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jlbTenAdmin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbTenAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTenAdmin.setText("Admin");

        jcbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UserName", "Họ tên", "Địa chỉ", "Số điện thoại", "Chức vụ", "Tất cả" }));

        jButton6.setText("Đăng xuất");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbTenAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jcbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jlbType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbTenAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfSearch)
                    .addComponent(jcbSearch)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        jPanel3.setLayout(new java.awt.GridLayout(6, 2));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Username");
        jPanel3.add(jLabel5);
        jPanel3.add(jtfUserName);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        jPanel3.add(jLabel4);
        jPanel3.add(jpwPass);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Chức vụ");
        jPanel3.add(jLabel6);

        jcbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Admin", "Employee" }));
        jcbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRoleActionPerformed(evt);
            }
        });
        jPanel3.add(jcbRole);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Họ tên");
        jPanel3.add(jLabel3);
        jPanel3.add(jtfHoTen);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Địa chỉ");
        jPanel3.add(jLabel7);
        jPanel3.add(jtfDiaChi);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Số điện thoại");
        jPanel3.add(jLabel8);
        jPanel3.add(jtfSoDT);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jButton4.setText("Thoát");
        jPanel4.add(jButton4);

        jtbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Hàm thêm 1 tài khoản vào trong cơ sở dữ liệu*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        /*Các hàm dùng để bắt lỗi nhập sai của người dùng*/
        if (!BatNgoaiLe.loiString(jtfUserName.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfUserName.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jpwPass.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jpwPass.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfHoTen.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfHoTen.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfDiaChi.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfDiaChi.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfSoDT.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfSoDT.requestFocus();
            return;
        }
        
        /*Hỏi người dùng có đồn ý thêm tài khoản vào csdl không*/
        int luaChon = JOptionPane.showConfirmDialog(this, "Thông tin tai khoan\n"
                + "UserName:" + jtfUserName.getText() + "\n"
                + "PassWord:" + jpwPass.getText() + "\n"
                + "Họ tên: " + jtfHoTen.getText() + "\n"
                + "Địa chỉ:" + jtfDiaChi.getText() + "\n"
                + "Số điện thoại: " + jtfSoDT.getText() + "\n"
                + "Chức vụ: " + jcbRole.getSelectedItem().toString());
        if (luaChon == JOptionPane.YES_NO_OPTION) { //Đồng ý ==> thêm vào csdl
            TaiKhoan taiKhoan = new TaiKhoan(0, jtfUserName.getText(), jpwPass.getText(), jtfHoTen.getText(),
                    jtfDiaChi.getText(), jtfSoDT.getText(), jcbRole.getSelectedItem().toString());
            boolean check = taiKhoanDAO.themTaiKhoan(taiKhoan);
            if (check == true) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "UserName đã có người sử dụng!");
                jtfUserName.requestFocus();
                return;
            }
        }
        v = taiKhoanDAO.danhSachTaiKhoan();
        setTBUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    /*Hàm bắt sự kiện click vào bảng dữ liệu*/
    private void jtbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUserMouseClicked
        
        /*Khi click vào 1 dòng của bảng thì dữ liệu của bảng đó sẽ đc show lên form*/
        int hang = jtbUser.getSelectedRow();
        if (hang != -1) {
            jtfUserName.setText(jtbUser.getValueAt(hang, 1).toString());
            jpwPass.setText(jtbUser.getValueAt(hang, 2).toString());
            jtfHoTen.setText(jtbUser.getValueAt(hang, 3).toString());
            jtfDiaChi.setText(jtbUser.getValueAt(hang, 4).toString());
            jtfSoDT.setText(jtbUser.getValueAt(hang, 5).toString());
            jcbRole.setSelectedItem(jtbUser.getValueAt(hang, 6));
            idChon = Integer.parseInt(jtbUser.getValueAt(hang, 0).toString());
        }
    }//GEN-LAST:event_jtbUserMouseClicked

    int idChon;
    /*Hàm sửa tài khoản*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        /*Bắt lỗi người dùng*/
        if (!BatNgoaiLe.loiString(jtfUserName.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfUserName.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jpwPass.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jpwPass.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfHoTen.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfHoTen.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfDiaChi.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfDiaChi.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfSoDT.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu");
            jtfSoDT.requestFocus();
            return;
        }
        
        /*Hỏi xem có đồng ý sửa không?*/
        int luaChon = JOptionPane.showConfirmDialog(this, "Thông tin tài khoản\n"
                + "UserName:" + jtfUserName.getText() + "\n"
                + "PassWord:" + jpwPass.getText() + "\n"
                + "Họ tên: " + jtfHoTen.getText() + "\n"
                + "Địa chỉ:" + jtfDiaChi.getText() + "\n"
                + "Số điện thoại: " + jtfSoDT.getText() + "\n"
                + "Chức vụ: " + jcbRole.getSelectedItem().toString());
        if (luaChon == JOptionPane.YES_NO_OPTION) { //Đồng ý ==> sửa
            TaiKhoan taiKhoan = new TaiKhoan(0, jtfUserName.getText(), jpwPass.getText(), jtfHoTen.getText(),
                    jtfDiaChi.getText(), jtfSoDT.getText(), jcbRole.getSelectedItem().toString());
            boolean check = taiKhoanDAO.suaTaiKhoan(idChon, taiKhoan);
            if (check == true) {
                JOptionPane.showMessageDialog(this, "Sửa thành công thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Sửa thất bại!");
                jtfUserName.requestFocus();
                return;
            }
        }
        v = taiKhoanDAO.danhSachTaiKhoan();
        setTBUser();
    }//GEN-LAST:event_jButton2ActionPerformed

    /*Xóa một tài khoản*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /*Hỏi người dùng có muốn xóa k*/
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn xóa?");
        if (luaChon == JOptionPane.YES_OPTION) {    //Đồng ý ==> xóa
            try {
                boolean check = taiKhoanDAO.xoaTaiKhoan(idChon);
                if (check == true) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công!");
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa thất bại!");
                }
            } catch (Exception ex) {    //Ngoại lệ không chọn tài khoản nhưng vẫn click vào nút xóa
                JOptionPane.showMessageDialog(null, "Hãy chọn 1 user để xóa");
            }
        }
        v = taiKhoanDAO.danhSachTaiKhoan();
        setTBUser();
    }//GEN-LAST:event_jButton3ActionPerformed

    /*Tìm kiếm danh sách các tài khoản*/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String key = jtfSearch.getText().trim();
        switch (jcbSearch.getSelectedIndex()) {
            case 0:
                v = taiKhoanDAO.timKiemTheoUserName(key);
                break;
            case 1:
                v = taiKhoanDAO.timKiemTheoHoTen(key);
                break;
            case 2:
                v = taiKhoanDAO.timKiemTheoDiaChi(key);
                break;
            case 3:
                v = taiKhoanDAO.timKiemTheoSoDienThoai(key);
                break;
            case 4:
                v = taiKhoanDAO.timKiemTheoChucVu(key);
                break;
            case 5:
                v = taiKhoanDAO.timKiemTaiKhoan(key);
                break;
            default:
                throw new AssertionError();
        }
        setTBUser();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jcbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRoleActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         // TODO add your handling code here:
         this.setVisible(false);
         new FrmLogin().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbRole;
    private javax.swing.JComboBox<String> jcbSearch;
    private javax.swing.JLabel jlbTenAdmin;
    private javax.swing.JLabel jlbType;
    private javax.swing.JPasswordField jpwPass;
    private javax.swing.JTable jtbUser;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfSoDT;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
