/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.manager.quanlyphim;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Phim;
import control.PhimDAO;
import javax.swing.UIManager;
import model.TaiKhoan;
import support.BatNgoaiLe;

/**
 *
 * @author MrDuc
 */
public class FrmSuaPhim extends javax.swing.JFrame {

    private Phim f = new Phim();
    private TaiKhoan taiKhoan;

    /**
     * Creates new form FrmSuaPhim
     */
    public FrmSuaPhim() {
        initComponents();
    }

    public FrmSuaPhim(Phim phim, TaiKhoan tk) {
        taiKhoan = tk;
        initComponents();
        f = phim;
        setTT();
    }

    /*Set các thuộc tính ban đầu của phim cần sửa*/
    public void setTT() {
        try {
            SimpleDateFormat spd = new SimpleDateFormat("yyyy'-'MM'-'dd");
            jtfTenPhim.setText(f.getTenPhim());
            jtfDaoDien.setText(f.getDaoDien());
            jtfTheLoai.setText(f.getTheLoai());
            jdcNgayKhoiChieu.setDate(spd.parse(f.getNgayKhoiChieu()));
            jtfThoiLuong.setText(f.getThoiLuong() + "");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfTenPhim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDaoDien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfTheLoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdcNgayKhoiChieu = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jtfThoiLuong = new javax.swing.JTextField();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        Content.setLayout(new java.awt.GridLayout(5, 2));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên phim");
        Content.add(jLabel2);
        Content.add(jtfTenPhim);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đạo diễn");
        Content.add(jLabel3);
        Content.add(jtfDaoDien);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thể loại phim");
        Content.add(jLabel6);
        Content.add(jtfTheLoai);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày khởi chiếu");
        Content.add(jLabel4);
        Content.add(jdcNgayKhoiChieu);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Thời lượng phim (Phút)");
        Content.add(jLabel5);
        Content.add(jtfThoiLuong);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa Phim");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Footer.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));
        Footer.setLayout(new java.awt.GridLayout(1, 3));

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Footer.add(jButton1);

        jButton2.setText("Mặc Định");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Footer.add(jButton2);

        jButton3.setText("Trở lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Footer.add(jButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmTimKiemSua(taiKhoan).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setTT();
    }//GEN-LAST:event_jButton2ActionPerformed

    /*Sửa thông tin của phim*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!BatNgoaiLe.loiString(jtfTenPhim.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu! Mời nhập lại!");
            jtfTenPhim.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfDaoDien.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu! Mời nhập lại!");
            jtfDaoDien.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiString(jtfTheLoai.getText())) {
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu! Mời nhập lại!");
            jtfTheLoai.requestFocus();
            return;
        }
        if (!BatNgoaiLe.loiInt(jtfThoiLuong.getText())) {
            JOptionPane.showMessageDialog(null, "Sai định dạng dữ liệu! Mời nhập lại!");
            jtfThoiLuong.requestFocus();
            return;
        }
        PhimDAO phimDAO = new PhimDAO();
        Date date = jdcNgayKhoiChieu.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy'-'MM'-'dd");
        int luaChon = JOptionPane.showConfirmDialog(this, "Thông tin phim\n"
                + "Tên phim:" + jtfTenPhim.getText() + "\n"
                + "Đạo diễn:" + jtfDaoDien.getText() + "\n"
                + "Ngày khởi chiếu: " + sdf.format(date) + "\n"
                + "Thể loại phim: " + jtfTheLoai.getText() + "\n"
                + "Thời lượng phim: " + jtfThoiLuong.getText() + " phút");
        if (luaChon == JOptionPane.YES_NO_OPTION) {
            Phim film = new Phim(f.getMaPhim(), jtfTenPhim.getText(), jtfTheLoai.getText(), jtfDaoDien.getText(),
                    sdf.format(date), Integer.parseInt(jtfThoiLuong.getText()));
            boolean check = phimDAO.suaPhim(f.getMaPhim(), film);
            if (check == true) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                f = film;
            } else {
                JOptionPane.showMessageDialog(null, "Sửa thất bại!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSuaPhim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser jdcNgayKhoiChieu;
    private javax.swing.JTextField jtfDaoDien;
    private javax.swing.JTextField jtfTenPhim;
    private javax.swing.JTextField jtfTheLoai;
    private javax.swing.JTextField jtfThoiLuong;
    // End of variables declaration//GEN-END:variables
}
