/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.manager.quanlyphong;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.Phim;
import model.PhongChieu;
import control.PhimDAO;
import control.PhongDAO;
import javax.swing.UIManager;
import model.TaiKhoan;
import view.manager.quanlyphim.*;

/**
 *
 * @author MrDuc
 */
public class FrmTimKiemSua extends javax.swing.JFrame {

    private TaiKhoan taiKhoan;
    private Vector<PhongChieu> v = new Vector<>();
    private PhongChieu phongChieu = new PhongChieu();
    PhongDAO phongDAO = new PhongDAO();

    /**
     * Creates new form FrmTimKiemSua
     */
    public FrmTimKiemSua() {
        initComponents();
        v = phongDAO.danhSachPhong();
        setTB();
    }

    public FrmTimKiemSua(TaiKhoan tk) {
        initComponents();
        taiKhoan = tk;
        v = phongDAO.danhSachPhong();
        setTB();
    }

    public void setTB() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers("Mã phòng, Tên phòng, Số ghế, Loại phòng, Mô tả".split(","));
        for (PhongChieu phongChieu : v) {
            dtm.addRow(phongChieu.getObject());
        }
        jtbDanhSachPhong.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfKey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDanhSachPhong = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jcbTimKiem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa Thông Tin Phòng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Zoom-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtbDanhSachPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbDanhSachPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDanhSachPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDanhSachPhong);

        jButton3.setText("Trở lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jcbTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã phòng", "Tên phòng", "Loại phòng", "Số lượng ghế", "Tìm kiếm nhanh" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jtfKey, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jcbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfKey)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmQuanLyPhong(taiKhoan).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String key = jtfKey.getText().trim();
        int choice = jcbTimKiem.getSelectedIndex();
        switch (choice) {
            case 0:
                v = phongDAO.timKiemTheoMaPhong(key);
                break;
            case 1:
                v = phongDAO.timKiemTheoTenPhong(key);
                break;
            case 2:
                v = phongDAO.timKiemTheoLoaiPhong(key);
                break;
            case 3:
                v = phongDAO.timKiemTheoSoGhe(key);
                break;
            case 4:
                v = phongDAO.timKiemPhong(key);
                break;
            default:
                throw new AssertionError();
        }
        setTB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtbDanhSachPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDanhSachPhongMouseClicked
        // TODO add your handling code here:
        int hang = jtbDanhSachPhong.getSelectedRow();
        phongChieu.setMaPhong(jtbDanhSachPhong.getValueAt(hang, 0).toString());
        phongChieu.setTenPhong(jtbDanhSachPhong.getValueAt(hang, 1).toString());
        phongChieu.setSoGhe(Integer.parseInt(jtbDanhSachPhong.getValueAt(hang, 2).toString()));
        phongChieu.setLoaiPhong(jtbDanhSachPhong.getValueAt(hang, 3).toString());
        phongChieu.setMoTa(jtbDanhSachPhong.getValueAt(hang, 4).toString());
    }//GEN-LAST:event_jtbDanhSachPhongMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmSuaPhong(phongChieu, taiKhoan).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTimKiemSua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbTimKiem;
    private javax.swing.JTable jtbDanhSachPhong;
    private javax.swing.JTextField jtfKey;
    // End of variables declaration//GEN-END:variables
}
